language: android

android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.m2
